version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ./Backend
    env_file: ./Backend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./Frontend
    env_file: ./Frontend/.env.local
    ports:
      - "5173:5173"